# Generated by Django 4.2.13 on 2026-05-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='label_height_mm',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='label_width_mm',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='receipt_footer',
            field=models.TextField(blank=True, default='Thank you! Visit again.'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='receipt_header',
            field=models.TextField(blank=True, help_text='Extra lines on bill (one per line)'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='receipt_show_barcode',
            field=models.BooleanField(default=True, help_text='Print bill barcode on receipt'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='receipt_width_mm',
            field=models.PositiveSmallIntegerField(choices=[(58, '58 mm (2 inch)'), (80, '80 mm (3 inch / TVS)')], default=80),
        ),
    ]
