# Generated by Django 4.2.13 on 2026-05-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_purchase_created_at_purchase_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST % on this product', max_digits=5),
        ),
        migrations.AddField(
            model_name='purchase',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='invoice_prefix',
            field=models.CharField(default='S7', max_length=10),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='store_name',
            field=models.CharField(default='SEE7 CLOTHINGS', max_length=150),
        ),
    ]
